apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: go-rimegate-dogelink-com
  name: go-rimegate-dogelink-com
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: go-rimegate-dogelink-com
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-rimegate-dogelink-com
    spec:
      containers:
      - env:
        - name: GRAFANA_API_KEY
          valueFrom:
            secretKeyRef:
              key: secret
              name: grafana-read-only-token
        - name: GRAFANA_HOST
          value: "http://grafana.monitoring.svc.cluster.local"
        image: 172.16.16.2:2443/go:rimegate-pending
        imagePullPolicy: IfNotPresent
        name: rimegate
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 384Mi
          requests:
            cpu: 150m
            memory: 192Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: go-images-ebornet-com
  namespace: monitoring
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-rimegate-dogelink-com
  sessionAffinity: None
  type: ClusterIP